services:
  app-dev:
    build: .
    container_name: cambioao-app-dev
    restart: unless-stopped
    env_file: .env
    ports:
      - "3000:3000"
    volumes:
      # Esta linha Ã© a chave: mapeia a sua pasta 'public' local
      # para a pasta 'public' dentro do contentor.
      - ./public:/usr/src/app/public
      - sessions_data:/usr/src/app/sessions

volumes:
  sessions_data:
